#!/system/bin/sh
# Copyright (c) 2017, Stripalov. All rights reserved.
# Check setting state
state=`settings get system perf`;
enabled=1;
if [ "$state" -eq "$enabled" ]; then
# Show message in logcat output
	echo Performance mode is enabled. Switching CPU, GPU and DDR governor...
else
# Run toogle script
	sh /system/bin/disable_perf && exit
fi
msg -n Включен производительный режим title=Внимание
# Disable CPU thermal protection
echo 0 > /sys/module/msm_thermal/core_control/enabled
# Enable performance governor
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo performance > /sys/devices/soc.0/1c00000.qcom,kgsl-3d0/devfreq/1c00000.qcom,kgsl-3d0/governor
echo performance > /sys/devices/soc.0/qcom,cpubw.30/devfreq/qcom,cpubw.30/governor
# Apply gaming tweaks
echo 1 > /sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/force_bus_on
echo 1 > /sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/force_rail_on
echo 1 > /sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/force_clk_on
echo 1000000 > /sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/idle_timer
# Enable CPU thermal protection
echo 1 > /sys/module/msm_thermal/core_control/enabled
