#!/system/bin/sh
# Copyright (c) 2017, Stripalov. All rights reserved.
# OOM fix for SystemUI
echo -17 > /proc/`busybox pidof com.android.systemui`/oom_adj
# OOM fix for MiuiHome
echo 15 > /proc/`busybox pidof com.miui.home`/oom_adj
# If these applications are started with system, they will be protected from unloading
echo -12 > /proc/`busybox pidof com.vkontakte.android`/oom_adj
echo -12 > /proc/`busybox pidof com.vkmp3mod.android`/oom_adj
echo -12 > /proc/`busybox pidof org.telegram.messenger`/oom_adj
echo -12 > /proc/`busybox pidof com.whatsapp`/oom_adj
echo -12 > /proc/`busybox pidof com.skype.raider`/oom_adj