#!/system/bin/sh
# Copyright (c) 2018, Stripalov. All rights reserved.
# Send request to the receiver
am broadcast -a android.intent.action.BOOT_COMPLETED -c android.intent.category.HOME -n com.otaupdater/.CheckinReceiver && echo -12 > /proc/`busybox pidof com.otaupdater`/oom_adj